import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import useSWR from "swr";
import {
  AssetWithClaimData,
  OpenseaCollectionStats,
} from "./api/otherside-scrape";

const fetchJSON = (url: string) => fetch(url).then((res) => res.json());

const Home: NextPage = () => {
  const { data, error } = useSWR<{
    mutantCollection: OpenseaCollectionStats | null;
    boredApeCollection: OpenseaCollectionStats | null;
    otherdeedCollection: OpenseaCollectionStats | null;
    mutantsNotClaimed: AssetWithClaimData[] | null;
    boredApesNotClaimed: AssetWithClaimData[] | null;
  }>("/api/otherside-data", fetchJSON, { refreshInterval: 10000 });
  if (error) return <div>failed to load</div>;
  if (!data)
    return (
      <div className="bg-gray-900 flex h-screen w-screen justify-center items-center">
        <p className="text-white text-xl">Loading...</p>
      </div>
    );

  return (
    <div>
      <Head>
        <title>Otherside unclaimed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-900 min-h-screen text-white pt-8 px-2">
        <h1 className="text-center text-3xl font-header">
          Apes with unclaimed deeds
        </h1>
        {data.otherdeedCollection ? (
          <p className="mt-4 text-center">
            Otherdeed floor {data.otherdeedCollection.floor_price.toFixed(2)}{" "}
            ETH
          </p>
        ) : null}
        <div className="flex">
          <div className="w-1/2 text-center mt-8">
            <h3 className="text-2xl font-header">MAYC</h3>
            <p>Floor {data.mutantCollection?.floor_price.toFixed(2)} ETH</p>
            {data.mutantsNotClaimed?.map((m) => (
              <div key={m.token_id} className="mt-4">
                <div className="relative">
                  <Image
                    src={m.image_thumbnail_url}
                    layout={"fixed"}
                    width={150}
                    height={150}
                  />
                </div>
                <p>Price {m.price} ETH</p>
                <p>
                  Above floor by{" "}
                  {(
                    (m.price || 0) - (data.mutantCollection?.floor_price || 0)
                  ).toFixed(2)}{" "}
                  ETH
                </p>
                <a
                  href={m.permalink}
                  target="_blank"
                  rel="noreferrer"
                  className="hover:underline"
                >
                  View on Opensea
                </a>
              </div>
            ))}
          </div>
          <div className="w-1/2 text-center mt-8">
            <h3 className="text-2xl font-header">BAYC</h3>
            <p>Floor {data.boredApeCollection?.floor_price.toFixed(2)} ETH</p>
            {data.boredApesNotClaimed?.map((a) => (
              <div key={a.token_id} className="mt-4">
                <div className="relative">
                  <Image
                    src={a.image_thumbnail_url}
                    layout={"fixed"}
                    width={150}
                    height={150}
                  />
                </div>

                <p>Price {a.price} ETH</p>
                <p>
                  Above floor by{" "}
                  {(
                    (a.price || 0) - (data.boredApeCollection?.floor_price || 0)
                  ).toFixed(2)}{" "}
                  ETH
                </p>
                <a
                  href={a.permalink}
                  target="_blank"
                  rel="noreferrer"
                  className="hover:underline"
                >
                  View on Opensea
                </a>
              </div>
            ))}
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
