import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import useSWR from "swr";
import {
  AssetWithClaimData,
  OpenseaCollectionStats,
} from "./api/otherside-scrape";

const fetchJSON = (url: string) => fetch(url).then((res) => res.json());

const Home: NextPage = () => {
  const { data, error } = useSWR<{
    mutantCollection: OpenseaCollectionStats | null;
    boredApeCollection: OpenseaCollectionStats | null;
    mutantsNotClaimed: AssetWithClaimData[] | null;
    boredApesNotClaimed: AssetWithClaimData[] | null;
  }>("/api/otherside-data", fetchJSON);
  if (error) return <div>failed to load</div>;
  if (!data) return <div>loading...</div>;
  console.log(data);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex">
          <div>
            {data.mutantsNotClaimed?.map((m) => (
              <div key={m.token_id}>
                <div className="relative">
                  <Image
                    src={m.image_thumbnail_url}
                    layout={"fixed"}
                    width={150}
                    height={150}
                  />
                </div>
                <p>Floor {data.mutantCollection?.floor_price}</p>
                <p>Price {m.price}</p>
                <p>
                  Difference{" "}
                  {(m.price || 0) - (data.mutantCollection?.floor_price || 0)}
                </p>
                <a href={m.permalink} target="_blank" rel="noreferrer">
                  Link
                </a>
              </div>
            ))}
          </div>{" "}
          <div>
            {data.boredApesNotClaimed?.map((a) => (
              <div key={a.token_id}>
                <div className="relative">
                  <Image
                    src={a.image_thumbnail_url}
                    layout={"fixed"}
                    width={150}
                    height={150}
                  />
                </div>
                <p>Floor {data.boredApeCollection?.floor_price}</p>
                <p>Price {a.price}</p>
                <p>
                  Difference{" "}
                  {(a.price || 0) - (data.boredApeCollection?.floor_price || 0)}
                </p>
                <a href={a.permalink} target="_blank" rel="noreferrer">
                  Link
                </a>
              </div>
            ))}
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
