import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";

const Home: NextPage = () => {
  useEffect(() => {
    fetch("/api/trait-snipe");
  }, []);

  return (
    <div>
      <Head>
        <title>Sniper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">Sniper</h1>
      </main>
    </div>
  );
};

export default Home;
